INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (101, 'Rodrigo Santana', 'rodrigo.santana@email.com', TO_DATE('2019-04-15', 'YYYY-MM-DD'), 'A', 'Sul');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (102, 'Mariana Costa', 'mariana.costa@email.com', TO_DATE('2020-09-22', 'YYYY-MM-DD'), 'A', 'Sudeste');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (103, 'Lucas Oliveira', 'lucas.oliveira@email.com', TO_DATE('2018-12-01', 'YYYY-MM-DD'), 'A', 'Nordeste');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (106, 'Ana Paula Martins', 'ana.martins@email.com', TO_DATE('2021-07-18', 'YYYY-MM-DD'), 'A', 'Sul');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (112, 'Fernando Almeida', 'fernando.almeida@email.com', TO_DATE('2022-03-05', 'YYYY-MM-DD'), 'A', 'Norte');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (124, 'Camila Ferreira', 'camila.ferreira@email.com', TO_DATE('2023-01-30', 'YYYY-MM-DD'), 'A', 'Nordeste');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (152, 'Pedro Bruneto Macedo', 'pedrobunetoos@gmail.com', TO_DATE('2025-07-17', 'YYYY-MM-DD'), 'A', 'Sul');


INSERT INTO TABELA_DE_VENDEDORES 
  (MATRICULA, NOME, EMAIL, DATA_CADASTRO, STATUS_VENDEDOR, REGIAO) 
VALUES 
  (153, 'Lana Kass', 'laninhaaakss@gmail.com', TO_DATE('2025-07-12', 'YYYY-MM-DD'), 'A', 'Norte');