INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (201, 'Mariana Lima', 'Sudeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (202, 'Pedro Alves', 'Sul', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (203, 'Ana Rocha', 'Nordeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (203, 'Ana Rocha', 'Nordeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (204, 'Bruno Almeida de Moraes', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (205, 'Bianca Freitas', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (206, 'Athos Carter', 'Nordeste', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (207, 'Bryan O''brien', 'Norte', 112);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (208, 'Karla Lima', 'Sudeste', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (209, 'Felipe da Silva', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (210, 'Larissa Souza', 'Sudeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (211, 'Thiago Mendes', 'Sul', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (212, 'Camila Barreto', 'Nordeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (213, 'Lucas Ferreira', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (214, 'Aline Costa', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (215, 'Victor Hugo', 'Nordeste', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (216, 'Emily Torres', 'Norte', 112);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (217, 'Renan Oliveira', 'Sudeste', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (218, 'Fabiana Martins', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (219, 'Rafael Monteiro', 'Nordeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (220, 'Isabela Ramos', 'Sul', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (221, 'Gustavo Almeida', 'Nordeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (222, 'Sofia Nascimento', 'Sudeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (223, 'Bruno Costa', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (224, 'Luana Martins', 'Norte', 112);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (225, 'Ricardo Souza', 'Nordeste', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (226, 'Ana Clara Pereira', 'Sudeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (227, 'Marcelo Dias', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (228, 'Julia Fernandes', 'Nordeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (229, 'André Carvalho', 'Sudeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (230, 'Maria Eduarda Lima', 'Sudeste', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (231, 'Caio Henrique Silva', 'Sul', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (232, 'Mariana Figueiredo', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (233, 'Pedro Henrique Costa', 'Norte', 112);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (234, 'Letícia Alves', 'Sul', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (235, 'Fernando Oliveira', 'Sudeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (236, 'Aline Souza', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (237, 'Thiago Rodrigues', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (238, 'Luiza Martins', 'Sudeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (239, 'Bruna Santos', 'Sul', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (240, 'Paula Ribeiro', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (241, 'Diego Fernandes', 'Sudeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (242, 'Samantha Gomes', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (243, 'Rafael Moreira', 'Norte', 112);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (244, 'Carla Lopes', 'Sul', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (245, 'Bruno Santos', 'Sudeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (246, 'Renata Alves', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (247, 'Gustavo Pereira', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (248, 'Marina Oliveira', 'Sudeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (249, 'Fabio Carvalho', 'Sul', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (250, 'Lucas Fernandes', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (251, 'Ana Paula Mendes', 'Sudeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (252, 'Thiago Almeida', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (253, 'Mariana Costa', 'Norte', 112);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (254, 'Felipe Oliveira', 'Sul', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (255, 'Carolina Rodrigues', 'Sudeste', 103);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (256, 'Pedro Santos', 'Sul', 106);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (257, 'Julia Lima', 'Nordeste', 102);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (258, 'André Moreira', 'Sudeste', 101);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (259, 'Renata Silva', 'Sul', 124);

INSERT INTO
  TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA)
VALUES
  (260, 'Vinicius Pereira', 'Nordeste', 106);