-- Puxa as tabelas para visualização


SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_VENDEDORES;


-- Verifica cliente atendido por vendedor


SELECT 
  TV.MATRICULA AS MATRICULA_VENDEDOR,
  TC.NOME AS NOME_CLIENTE,
  TC.ID_CLIENTE AS IDENTIFICACAO_CLIENTE
FROM 
  TABELA_DE_CLIENTES TC
INNER JOIN 
  TABELA_DE_VENDEDORES TV
ON
  TV.MATRICULA = TC.MATRICULA
ORDER BY 
  TC.NOME, TV.MATRICULA, TC.ID_CLIENTE;
  

-- Quantos clientes cada vendedor atende


SELECT 
  TV.MATRICULA AS MATRICULA_VENDEDOR,
  COUNT(*) AS TOTAL_CLIENTES
FROM 
  TABELA_DE_CLIENTES TC
INNER JOIN 
  TABELA_DE_VENDEDORES TV
ON
  TV.MATRICULA = TC.MATRICULA
GROUP BY
  TV.MATRICULA
ORDER BY 
  TV.MATRICULA;