SELECT * FROM TABELA_DE_VENDEDORES;

-- Vendedores dos estados Sul e Norte

SELECT NOME AS NOME_VENDEDOR, REGIAO AS REGIAO_VENDEDOR 
     FROM TABELA_DE_VENDEDORES 
     WHERE REGIAO IN ('Sul', 'Norte')
     ORDER BY NOME_VENDEDOR;
     
-- Vendedores somente estado Norte (filtro por região)

SELECT NOME AS NOME_VENDEDOR, REGIAO AS REGIAO_VENDEDOR
     FROM TABELA_DE_VENDEDORES
     WHERE REGIAO = 'Norte'
     ORDER BY NOME_VENDEDOR;
     
-- Data de Cadastro Recente (filtro por data)

SELECT NOME AS NOME_VENDEDOR, DATA_CADASTRO AS DATA_CADASTRO_VENDEDOR 
     FROM TABELA_DE_VENDEDORES
     WHERE DATA_CADASTRO > TO_DATE('10/07/25', 'DD/MM/YY');