SELECT * FROM TABELA_DE_CLIENTES;

-- Clientes atendidos pelo vendedor 102

SELECT NOME, REGIAO, MATRICULA AS MATRICULA_VENDEDOR
    FROM TABELA_DE_CLIENTES
    WHERE MATRICULA = 102
    ORDER BY NOME, REGIAO, MATRICULA_VENDEDOR;
    
-- Clientes atendidos pelo vendedor 124

SELECT NOME, REGIAO, MATRICULA AS MATRICULA_VENDEDOR
    FROM TABELA_DE_CLIENTES
    WHERE MATRICULA = 124
    ORDER BY NOME, REGIAO, MATRICULA_VENDEDOR;
    
-- Quantidade de clientes por região

SELECT REGIAO, COUNT(*) AS TOTAL_DE_CLIENTES 
    FROM TABELA_DE_CLIENTES
    GROUP BY REGIAO
    ORDER BY REGIAO;
    
-- Clientes atendidos pela matrícula 102 e 101 (ordenados também)

SELECT NOME, MATRICULA 
     FROM TABELA_DE_CLIENTES 
     WHERE MATRICULA IN ('102', '101')
     ORDER BY NOME, MATRICULA;
     