SELECT * FROM TABELA_DE_NOTAS_FISCAIS;
SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM TABELA_DE_CLIENTES;

SELECT 
   TV.NOME AS NOME_VENDEDOR,
   TV.MATRICULA AS MATRICULA_VENDEDOR,
   TN.ID_NOTA AS IDENTIFICACAO_NOTA,
   TC.NOME AS NOME_CLIENTE
FROM 
   TABELA_DE_NOTAS_FISCAIS TN
INNER JOIN 
   TABELA_DE_VENDEDORES TV
ON 
   TN.MATRICULA = TV.MATRICULA
INNER JOIN
   TABELA_DE_CLIENTES TC
ON 
   TN.ID_CLIENTE = TC.ID_CLIENTE
ORDER BY
   TN.ID_NOTA, TV.NOME, TV.MATRICULA, TC.NOME;
   
