SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_NOTAS_FISCAIS;

-- Filtro Nome_Cliente | Regiao_Cliente | Identificacao_Produto | Nome_Produto | Identificacao_Nota 

SELECT 
   TC.NOME AS NOME_CLIENTE,
   TC.REGIAO AS REGIAO_CLIENTE,
   TP.ID_PRODUTO AS IDENTIFICACAO_PRODUTO,
   TP.NOME AS NOME_PRODUTO,
   TN.ID_NOTA AS IDENTIFICACAO_NOTA
FROM 
   TABELA_DE_NOTAS_FISCAIS TN
INNER JOIN
   TABELA_DE_PRODUTOS TP
ON 
   TP.ID_PRODUTO = TN.ID_PRODUTO
INNER JOIN 
   TABELA_DE_CLIENTES TC
ON 
   TC.ID_CLIENTE = TN.ID_CLIENTE
ORDER BY
   TC.NOME, TC.REGIAO, TP.ID_PRODUTO, TP.NOME, TN.ID_NOTA;


-- Filtrando clientes específicos

SELECT 
   TC.NOME AS NOME_CLIENTE,
   TC.REGIAO AS REGIAO_CLIENTE,
   TP.ID_PRODUTO AS IDENTIFICACAO_PRODUTO,
   TP.NOME AS NOME_PRODUTO,
   TN.ID_NOTA AS IDENTIFICACAO_NOTA
FROM 
   TABELA_DE_NOTAS_FISCAIS TN
INNER JOIN
   TABELA_DE_PRODUTOS TP
ON 
   TP.ID_PRODUTO = TN.ID_PRODUTO
INNER JOIN 
   TABELA_DE_CLIENTES TC
ON 
   TC.ID_CLIENTE = TN.ID_CLIENTE
WHERE
   TC.NOME IN('Rafael Moreira', 'Renan Oliveira', 'Samantha Gomes') 
ORDER BY
   TC.NOME, TC.REGIAO, TP.ID_PRODUTO, TP.NOME, TN.ID_NOTA;