-- Definindo a estrutura das tabelas

CREATE TABLE TABELA_DE_PRODUTOS (
   ID_PRODUTO NUMBER PRIMARY KEY,
   NOME VARCHAR2(100),
   MARCA VARCHAR2(50),
   CATEGORIA VARCHAR2(50),
   DATA_CADASTRO DATE,
   DESCRICAO_PRODUTO VARCHAR2(255),
   PRECO NUMBER(10,2),
   ESTOQUE NUMBER
);

CREATE TABLE TABELA_DE_VENDEDORES (
   MATRICULA NUMBER PRIMARY KEY,
   NOME VARCHAR2(100),
   EMAIL VARCHAR2(150),
   DATA_CADASTRO DATE,
   STATUS_VENDEDOR CHAR(1),
   REGIAO VARCHAR2(50)
);

CREATE TABLE TABELA_DE_NOTAS_FISCAIS (
   ID_NOTA NUMBER PRIMARY KEY,
   DATA DATE,
   MATRICULA NUMBER,
   ID_PRODUTO NUMBER,
   ID_CLIENTE NUMBER,
   QUANTIDADE NUMBER
);

CREATE TABLE TABELA_DE_CLIENTES (
   ID_CLIENTE NUMBER PRIMARY KEY,
   NOME VARCHAR2(100),
   REGIAO VARCHAR2(50),
   MATRICULA NUMBER
);

-- Alterando algumas tabelas para definir chaves estrangeiras

ALTER TABLE TABELA_DE_NOTAS_FISCAIS
ADD CONSTRAINT FK_TABELA_DE_VENDEDORES FOREIGN KEY (MATRICULA)
REFERENCES TABELA_DE_VENDEDORES(MATRICULA);


ALTER TABLE TABELA_DE_NOTAS_FISCAIS
ADD CONSTRAINT FK_TABELA_DE_PRODUTOS FOREIGN KEY (ID_PRODUTO)
REFERENCES TABELA_DE_PRODUTOS(ID_PRODUTO);


ALTER TABLE TABELA_DE_NOTAS_FISCAIS
ADD CONSTRAINT FK_TABELA_DE_CLIENTES FOREIGN KEY (ID_CLIENTE)
REFERENCES TABELA_DE_CLIENTES (ID_CLIENTE);


ALTER TABLE TABELA_DE_CLIENTES
ADD CONSTRAINT FK_TABELA_DE_CLIENTES FOREIGN KEY (MATRICULA)
REFERENCES TABELA_DE_VENDEDORES(MATRICULA);