CREATE TABLE TABELA_DE_PRODUTOS (
   ID_PRODUTO NUMBER PRIMARY KEY,
   NOME VARCHAR2(100),
   MARCA VARCHAR2(50),
   CATEGORIA VARCHAR2(50),
   PRECO NUMBER(10,2),
   ESTOQUE NUMBER
);

CREATE TABLE TABELA_DE_VENDEDORES (
   MATRICULA NUMBER PRIMARY KEY,
   NOME VARCHAR2(100),
   REGIAO VARCHAR2(50)
);

CREATE TABLE NOTAS_FISCAIS (
   ID_NOTA NUMBER PRIMARY KEY,
   DATA DATE,
   MATRICULA NUMBER,
   ID_PRODUTO NUMBER,
   QUANTIDADE NUMBER
);


ALTER TABLE NOTAS_FISCAIS
ADD CONSTRAINT FK_TABELA_DE_VENDEDORES FOREIGN KEY (MATRICULA)
REFERENCES TABELA_DE_VENDEDORES(MATRICULA);


ALTER TABLE NOTAS_FISCAIS
ADD CONSTRAINT FK_TABELA_DE_PRODUTOS FOREIGN KEY (ID_PRODUTO)
REFERENCES TABELA_DE_PRODUTOS(ID_PRODUTO);