INSERT INTO TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA) VALUES (201, 'Mariana Lima', 'Sudeste', 102);
INSERT INTO TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA) VALUES (202, 'Pedro Alves', 'Sul', 101);
INSERT INTO TABELA_DE_CLIENTES (ID_CLIENTE, NOME, REGIAO, MATRICULA) VALUES (203, 'Ana Rocha', 'Nordeste', 103);